dist: trusty
language: ruby
rvm: 2.5.1
addons:
  postgresql: 9.6
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
after_script:
  - bundle exec rake coveralls:push
install: bundle install --jobs=3 --retry=3
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rspec
services:
  - redis-server
