default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: <%= ENV['TRANSLATOR_DATABASE_USERNAME'] %>
  password: <%= ENV['TRANSLATOR_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: translator_development

test:
  <<: *default
  database: translator_test

production:
  <<: *default
  database: translator_production
