Locale.create(code: 'en', country_code: 'GB', names: { en: 'English', ru: 'Английский', da: 'Engelsk', fr: 'Anglais', de: 'Englisch', es: 'Inglés', pt: 'Inglês', el: 'Αγγλικά', uk: 'Англійська', nl: 'Engels' })
Locale.create(code: 'ru', country_code: 'RU', names: { en: 'Russian', ru: 'Русский', da: 'Russisk', fr: 'Russe', de: 'Russisch', es: 'Ruso', pt: 'Russo', el: 'Αγγλικά', uk: 'Русский', nl: 'Russisch' })
Locale.create(code: 'da', country_code: 'DK', names: { en: 'Danish', ru: 'Датский', da: 'Dansk', fr: 'Danois', de: 'Dänisch', es: 'Danés', pt: 'Dinamarquês', el: 'Δανέζικα', uk: 'Данська', nl: 'Deens' })
Locale.create(code: 'fr', country_code: 'FR', names: { en: 'French', ru: 'Французский', da: 'Fransk', fr: 'Français', de: 'Französisch', es: 'Francés', pt: 'Francês', el: 'Γαλλικά', uk: 'Французький', nl: 'Frans' })
Locale.create(code: 'de', country_code: 'DE', names: { en: 'German', ru: 'Немецкий', da: 'Tysk', fr: 'Allemand', de: 'Deutsch', es: 'Alemán', pt: 'Alemão', el: 'Γερμανικά', uk: 'Німецький', nl: 'Duits' })
Locale.create(code: 'es', country_code: 'ES', names: { en: 'Spanish', ru: 'Испанский', da: 'Spansk', fr: 'Espagnol', de: 'Spanisch', es: 'Español', pt: 'Espanhol', el: 'Ισπανικά', uk: 'Іспанська', nl: 'Spaans' })
Locale.create(code: 'pt', country_code: 'PT', names: { en: 'Portuguese', ru: 'Португальский', da: 'Portugisisk', fr: 'Portugais', de: 'Portugiesisch', es: 'Portugués', pt: 'Português', el: 'Πορτογαλικά', uk: 'Португальська', nl: 'Portugees' })
Locale.create(code: 'uk', country_code: 'UA', names: { en: 'Ukrainian', ru: 'Украинский', da: 'Ukrainsk', fr: 'Ukrainien', de: 'Ukrainisch', es: 'Ucraniano', pt: 'Ucraniano', el: 'Ουκρανικά', uk: 'Український', nl: 'Oekraïens' })
Locale.create(code: 'nl', country_code: 'NL', names: { en: 'Dutch', ru: 'Нидерландский', da: 'Hollandsk', fr: 'Néerlandais', de: 'Niederländisch', es: 'Holandés', pt: 'Dutch', el: 'Ολλανδικά', uk: 'Нідерландський', nl: 'Nederlands' })
Locale.create(code: 'el', country_code: 'GR', names: { en: 'Greek', ru: 'Греческий', da: 'Græsk', fr: 'Grec', de: 'Griechisch', es: 'Griego', pt: 'Grego', el: 'Ελληνικά', uk: 'Грецький', nl: 'Grieks' })
Locale.create(code: 'be', country_code: 'BY', names: { en: 'Belorussian', ru: 'Белорусский', da: 'Hviderussiske', fr: 'Biélorusse', de: 'Weißrussisch', es: 'Bielorruso', pt: 'Bielorrusso', el: 'Λευκορωσίας', uk: 'Білоруський', nl: 'Wit-Russisch' })
Locale.create(code: 'bg', country_code: 'BG', names: { en: 'Bulgarian', ru: 'Болгарский', da: 'Bulgarsk', fr: 'Bulgare', de: 'Bulgarisch', es: 'Búlgaro', pt: 'Búlgaro', el: 'Βουλγαρικά', uk: 'Болгарський', nl: 'Bulgarian' })
Locale.create(code: 'cs', country_code: 'CZ', names: { en: 'Czech', ru: 'Чешский', da: 'Tjekkisk', fr: 'Tchèque', de: 'Tschechisch', es: 'Checo', pt: 'Checo', el: 'Τσεχική', uk: 'Чеський', nl: 'Tsjechisch' })
Locale.create(code: 'et', country_code: 'EE', names: { en: 'Estonian', ru: 'Эстонский', da: 'Estisk', fr: 'Estonien', de: 'Estnisch', es: 'Estonio', pt: 'Estoniano', el: 'Εσθονικά', uk: 'Естонський', nl: 'Estlands' })
Locale.create(code: 'fi', country_code: 'FI', names: { en: 'Finnish', ru: 'Финский', da: 'Finsk', fr: 'Finlandais', de: 'Finnisch', es: 'Finlandés', pt: 'Finlandês', el: 'Φινλανδικά', uk: 'Фінський', nl: 'Fins' })
Locale.create(code: 'hu', country_code: 'HU', names: { en: 'Hungarian', ru: 'Венгерский', da: 'Ungarsk', fr: 'Hongrie', de: 'Ungarisch', es: 'Húngaro', pt: 'Húngaro', el: 'Ουγγρικά', uk: 'Угорський', nl: 'Hongaars' })
Locale.create(code: 'it', country_code: 'IT', names: { en: 'Italian', ru: 'Итальянский', da: 'Italiensk', fr: 'Italien', de: 'Italienisch', es: 'Italiano', pt: 'Italiano', el: 'Ιταλικά', uk: 'Iталійський', nl: 'Italiaans' })
Locale.create(code: 'lt', country_code: 'LT', names: { en: 'Lithuanian', ru: 'Литовский', da: 'Litauisk', fr: 'Lituanien', de: 'Litauisch', es: 'Lituano', pt: 'Lituano', el: 'Λιθουανικά', uk: 'Литовський', nl: 'Litouws' })
Locale.create(code: 'lv', country_code: 'LV', names: { en: 'Latvian', ru: 'Латышский', da: 'Lettisk', fr: 'Letton', de: 'Lettisch', es: 'Letón', pt: 'Letão', el: 'Λετονίας', uk: 'Латвійська', nl: 'Lets' })
Locale.create(code: 'no', country_code: 'NO', names: { en: 'Norwegian', ru: 'Норвежский', da: 'Norsk', fr: 'Norwegian', de: 'Norwegisch', es: 'Noruego', pt: 'Norueguês', el: 'Νορβηγικά', uk: 'Норвезька', nl: 'Noors' })
Locale.create(code: 'pl', country_code: 'PL', names: { en: 'Polish', ru: 'Польский', da: 'Polsk', fr: 'Polonais', de: 'Polnisch', es: 'Polaco', pt: 'Polonês', el: 'Πολωνικά', uk: 'Польський', nl: 'Pools' })
Locale.create(code: 'ro', country_code: 'RO', names: { en: 'Romanian', ru: 'Румынский', da: 'Rumænsk', fr: 'Roumain', de: 'Rumänisch', es: 'Rumano', pt: 'Romeno', el: 'Ρουμανικά', uk: 'Румунський', nl: 'Roemeens' })
Locale.create(code: 'sk', country_code: 'SK', names: { en: 'Slovak', ru: 'Словацкий', da: 'Slovakisk', fr: 'Slovak', de: 'Slowakisch', es: 'Slovak', pt: 'Eslovaco', el: 'Σλοβακικά', uk: 'Словацька', nl: 'Slowaaks' })
Locale.create(code: 'sl', country_code: 'SI', names: { en: 'Slovenian', ru: 'Словенский', da: 'Slovensk', fr: 'Slovène', de: 'Slowenisch', es: 'Esloveno', pt: 'Esloveno', el: 'Σλοβενικά', uk: 'Словенська', nl: 'Sloveens' })
Locale.create(code: 'sr', country_code: 'RS', names: { en: 'Serbian', ru: 'Сербский', da: 'Serbisk', fr: 'Serbe', de: 'Serbisch', es: 'Serbio', pt: 'Sérvio', el: 'Σερβικά', uk: 'Сербський', nl: 'Servisch' })
Locale.create(code: 'sv', country_code: 'SE', names: { en: 'Swedish', ru: 'Шведский', da: 'Svensk', fr: 'Suédois', de: 'Schwedisch', es: 'Sueco', pt: 'Sueco', el: 'Σουηδικά', uk: 'Щведський', nl: 'Zweeds' })
Locale.create(code: 'hr', country_code: 'HR', names: { en: 'Croatian', ru: 'Хорватский', da: 'Kroatisk', fr: 'Croate', de: 'Kroatisch', es: 'Croata', pt: 'Croata', el: 'Κροατικά', uk: 'Хорватська', nl: 'Kroatisch' })

Framework.create(name: 'Ruby on Rails', extension: 'yml', service: 'RailsService')
Framework.create(name: 'ReactJS', extension: 'json', service: 'ReactService')
Framework.create(name: 'Laravel', extension: 'json', service: 'LaravelService')
Framework.create(name: '.NET', extension: 'resx', service: 'NetService')
Framework.create(name: 'iOS', extension: 'strings', service: 'IosService')
Framework.create(name: 'Android', extension: 'xml', service: 'AndroidService')
Framework.create(name: 'Yii', extension: 'php', service: 'YiiService')
